#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

%global shortname defender
%global _unitdir %{_sysconfdir}/systemd/system
%global _a1configdir /system%{_sysconfdir}
%global _a2configdir /opt/alien/system%{_sysconfdir}

Name:       harbour-defender

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Privacy watcher
Version:    0.4.0
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://openrepos.net/content/nodevel/defender
Source0:    %{name}-%{version}.tar.bz2
Source100:  %{name}.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   pyotherside-qml-plugin-python3-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  systemd
Conflicts:      sailfishos-hosts-adblock
Conflicts:      noadshosts

%description
Configurable adblocker and privacy tuner


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
mkdir -p %{buildroot}/%{_unitdir}
cp ../%{name}/%{name}.service %{buildroot}/%{_unitdir}/%{name}.service
cp ../%{name}/%{name}.timer %{buildroot}/%{_unitdir}/%{name}.timer
cp ../%{name}/%{name}.path %{buildroot}/%{_unitdir}/%{name}.path
mkdir -p %{buildroot}/%{_sysconfdir}
cp ../%{name}/qml/python/%{shortname}_default.conf %{buildroot}/%{_sysconfdir}/%{shortname}.conf
%qmake5_install

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%attr(0644,root,root) %{_unitdir}/%{name}.service
%attr(0644,root,root) %{_unitdir}/%{name}.timer
%attr(0644,root,root) %{_unitdir}/%{name}.path
# %config %{_sysconfdir}/%{shortname}.conf
%attr(0644,root,root) %{_sysconfdir}/%{shortname}.conf
%exclude %{_datadir}/%{name}/qml/python/*.pyc
%exclude %{_datadir}/%{name}/qml/python/*.pyo
%exclude %{_datadir}/%{name}/qml/python/python_hosts/*.pyc
%exclude %{_datadir}/%{name}/qml/python/python_hosts/*.pyo
# >> files
# << files


%post
[ -f %{_sysconfdir}/hosts ] && echo "/etc/hosts exists" || echo -e "127.0.0.1               localhost.localdomain localhost\n::1             localhost6.localdomain6 localhost6\n" >> %{_sysconfdir}/hosts
[ -f %{_sysconfdir}/hosts.editable ] && echo "/etc/hosts.editable exists" || cp %{_sysconfdir}/hosts %{_sysconfdir}/hosts.editable 2>/dev/null || :
# Android files
if [ -d "%{_a1configdir}" ]; then
  # Only if the dir exists
  [ -f %{_a1configdir}/hosts ] && echo "%{_a1configdir}/hosts.editable exists exists" || echo -e "127.0.0.1                   localhost\n" >> %{_a1configdir}/hosts
  [ -f %{_a1configdir}/hosts.editable ] && echo "%{_a1configdir}/hosts.editable exists" || cp %{_a1configdir}/hosts %{_a1configdir}/hosts.editable 2>/dev/null || :
fi
if [ -d "%{_a2configdir}" ]; then
  # Only if the dir exists
  [ -f %{_a2configdir}/hosts ] && echo "%{_a2configdir}/hosts.editable exists exists" || echo -e "127.0.0.1                   localhost\n" >> %{_a2configdir}/hosts
  [ -f %{_a2configdir}/hosts.editable ] && echo "%{_a2configdir}/hosts.editable exists" || cp %{_a2configdir}/hosts %{_a2configdir}/hosts.editable 2>/dev/null || :
fi
systemctl start %{name}.timer
systemctl enable %{name}.timer
systemctl start %{name}.path
systemctl enable %{name}.path
# >> install post
# << install post

%preun
# in case of removal
if [ "$1" = "0" ]; then
    systemctl stop %{name}.timer
    systemctl disable %{name}.timer
    systemctl stop %{name}.path
    systemctl disable %{name}.path
    [ -f %{_sysconfdir}/hosts.editable ] && cp %{_sysconfdir}/hosts.editable %{_sysconfdir}/hosts 2>/dev/null || echo "/etc/hosts.editable does not exist"
    [ -f %{_a1configdir}/hosts.editable ] && cp %{_a1configdir}/hosts.editable %{_a1configdir}/hosts 2>/dev/null || echo "%{_a1configdir}/hosts.editable does not exist"
    [ -f %{_a2configdir}/hosts.editable ] && cp %{_a2configdir}/hosts.editable %{_a2configdir}/hosts 2>/dev/null || echo "%{_a2configdir}/hosts.editable does not exist"
fi
